mcl_3dl:
  map_frame: "map"
  odom_frame: "base_link_back"
  accum_cloud: 1
  fake_imu: true
  lpf_step: 1.0
  num_particles: 150
  resample_var_yaw: 0.05
  resample_var_pitch: 0.1
  resample_var_roll: 0.1
  acc_var: 1.2
  likelihood:
    match_dist_min: 0.3
    match_output_dist: 0.1
    clip_far: 30
    num_points: 300
  beam:
    num_points: 0
    clip_far: 10
    clip_near: 0.5
  odom_err_lin_ang: 0.05
  odom_err_lin_lin: 0.1
  odom_err_ang_lin: 0.05
  odom_err_ang_ang: 0.03
  map_downsample_x: 0.05
  map_downsample_y: 0.05
  map_downsample_z: 0.05
  downsample_x: 0.05
  downsample_y: 0.05
  downsample_z: 0.05
  update_downsample_x: 0.05
  update_downsample_y: 0.05
  update_downsample_z: 0.05
obj_to_pointcloud:
  frame_id: "map"
  points_per_meter_sq: 1200.0
  downsample_grid: 0.1
pcd_to_pointcloud:
  frame_id: "map"
  latch: true
